use super::*;

impl Instruction {
    pub fn from_byte_prefixed(byte: u8) -> Option<Self> {
        match byte {
            // RLC
            0x00 => Some(Self::RLC(ArithmeticTarget::B)),
            0x01 => Some(Self::RLC(ArithmeticTarget::C)),
            0x02 => Some(Self::RLC(ArithmeticTarget::D)),
            0x03 => Some(Self::RLC(ArithmeticTarget::E)),
            0x04 => Some(Self::RLC(ArithmeticTarget::H)),
            0x05 => Some(Self::RLC(ArithmeticTarget::L)),
            0x06 => Some(Self::RLC(ArithmeticTarget::HL)),
            0x07 => Some(Self::RLC(ArithmeticTarget::A)),
            // RRC
            0x08 => Some(Self::RRC(ArithmeticTarget::B)),
            0x09 => Some(Self::RRC(ArithmeticTarget::C)),
            0x0A => Some(Self::RRC(ArithmeticTarget::D)),
            0x0B => Some(Self::RRC(ArithmeticTarget::E)),
            0x0C => Some(Self::RRC(ArithmeticTarget::H)),
            0x0D => Some(Self::RRC(ArithmeticTarget::L)),
            0x0E => Some(Self::RRC(ArithmeticTarget::HL)),
            0x0F => Some(Self::RRC(ArithmeticTarget::A)),
            // RL
            0x10 => Some(Self::RL(ArithmeticTarget::B)),
            0x11 => Some(Self::RL(ArithmeticTarget::C)),
            0x12 => Some(Self::RL(ArithmeticTarget::D)),
            0x13 => Some(Self::RL(ArithmeticTarget::E)),
            0x14 => Some(Self::RL(ArithmeticTarget::H)),
            0x15 => Some(Self::RL(ArithmeticTarget::L)),
            0x16 => Some(Self::RL(ArithmeticTarget::HL)),
            0x17 => Some(Self::RL(ArithmeticTarget::A)),
            // RR
            0x18 => Some(Self::RR(ArithmeticTarget::B)),
            0x19 => Some(Self::RR(ArithmeticTarget::C)),
            0x1A => Some(Self::RR(ArithmeticTarget::D)),
            0x1B => Some(Self::RR(ArithmeticTarget::E)),
            0x1C => Some(Self::RR(ArithmeticTarget::H)),
            0x1D => Some(Self::RR(ArithmeticTarget::L)),
            0x1E => Some(Self::RR(ArithmeticTarget::HL)),
            0x1F => Some(Self::RR(ArithmeticTarget::A)),
            // SLA
            0x20 => Some(Self::SLA(ArithmeticTarget::B)),
            0x21 => Some(Self::SLA(ArithmeticTarget::C)),
            0x22 => Some(Self::SLA(ArithmeticTarget::D)),
            0x23 => Some(Self::SLA(ArithmeticTarget::E)),
            0x24 => Some(Self::SLA(ArithmeticTarget::H)),
            0x25 => Some(Self::SLA(ArithmeticTarget::L)),
            0x26 => Some(Self::SLA(ArithmeticTarget::HL)),
            0x27 => Some(Self::SLA(ArithmeticTarget::A)),
            // SRA
            0x28 => Some(Self::SRA(ArithmeticTarget::B)),
            0x29 => Some(Self::SRA(ArithmeticTarget::C)),
            0x2A => Some(Self::SRA(ArithmeticTarget::D)),
            0x2B => Some(Self::SRA(ArithmeticTarget::E)),
            0x2C => Some(Self::SRA(ArithmeticTarget::H)),
            0x2D => Some(Self::SRA(ArithmeticTarget::L)),
            0x2E => Some(Self::SRA(ArithmeticTarget::HL)),
            0x2F => Some(Self::SRA(ArithmeticTarget::A)),
            // SWAP
            0x30 => Some(Self::SWAP(ArithmeticTarget::B)),
            0x31 => Some(Self::SWAP(ArithmeticTarget::C)),
            0x32 => Some(Self::SWAP(ArithmeticTarget::D)),
            0x33 => Some(Self::SWAP(ArithmeticTarget::E)),
            0x34 => Some(Self::SWAP(ArithmeticTarget::H)),
            0x35 => Some(Self::SWAP(ArithmeticTarget::L)),
            0x36 => Some(Self::SWAP(ArithmeticTarget::HL)),
            0x37 => Some(Self::SWAP(ArithmeticTarget::A)),
            // SRL
            0x38 => Some(Self::SRL(ArithmeticTarget::B)),
            0x39 => Some(Self::SRL(ArithmeticTarget::C)),
            0x3A => Some(Self::SRL(ArithmeticTarget::D)),
            0x3B => Some(Self::SRL(ArithmeticTarget::E)),
            0x3C => Some(Self::SRL(ArithmeticTarget::H)),
            0x3D => Some(Self::SRL(ArithmeticTarget::L)),
            0x3E => Some(Self::SRL(ArithmeticTarget::HL)),
            0x3F => Some(Self::SRL(ArithmeticTarget::A)),
            // BIT 0
            0x40 => Some(Self::BIT(ArithmeticTarget::B, 0)),
            0x41 => Some(Self::BIT(ArithmeticTarget::C, 0)),
            0x42 => Some(Self::BIT(ArithmeticTarget::D, 0)),
            0x43 => Some(Self::BIT(ArithmeticTarget::E, 0)),
            0x44 => Some(Self::BIT(ArithmeticTarget::H, 0)),
            0x45 => Some(Self::BIT(ArithmeticTarget::L, 0)),
            0x46 => Some(Self::BIT(ArithmeticTarget::HL, 0)),
            0x47 => Some(Self::BIT(ArithmeticTarget::A, 0)),
            // BIT 1
            0x48 => Some(Self::BIT(ArithmeticTarget::B, 1)),
            0x49 => Some(Self::BIT(ArithmeticTarget::C, 1)),
            0x4A => Some(Self::BIT(ArithmeticTarget::D, 1)),
            0x4B => Some(Self::BIT(ArithmeticTarget::E, 1)),
            0x4C => Some(Self::BIT(ArithmeticTarget::H, 1)),
            0x4D => Some(Self::BIT(ArithmeticTarget::L, 1)),
            0x4E => Some(Self::BIT(ArithmeticTarget::HL, 1)),
            0x4F => Some(Self::BIT(ArithmeticTarget::A, 1)),
            // BIT 2
            0x50 => Some(Self::BIT(ArithmeticTarget::B, 2)),
            0x51 => Some(Self::BIT(ArithmeticTarget::C, 2)),
            0x52 => Some(Self::BIT(ArithmeticTarget::D, 2)),
            0x53 => Some(Self::BIT(ArithmeticTarget::E, 2)),
            0x54 => Some(Self::BIT(ArithmeticTarget::H, 2)),
            0x55 => Some(Self::BIT(ArithmeticTarget::L, 2)),
            0x56 => Some(Self::BIT(ArithmeticTarget::HL, 2)),
            0x57 => Some(Self::BIT(ArithmeticTarget::A, 2)),
            // BIT 3
            0x58 => Some(Self::BIT(ArithmeticTarget::B, 3)),
            0x59 => Some(Self::BIT(ArithmeticTarget::C, 3)),
            0x5A => Some(Self::BIT(ArithmeticTarget::D, 3)),
            0x5B => Some(Self::BIT(ArithmeticTarget::E, 3)),
            0x5C => Some(Self::BIT(ArithmeticTarget::H, 3)),
            0x5D => Some(Self::BIT(ArithmeticTarget::L, 3)),
            0x5E => Some(Self::BIT(ArithmeticTarget::HL, 3)),
            0x5F => Some(Self::BIT(ArithmeticTarget::A, 3)),
            // BIT 4
            0x60 => Some(Self::BIT(ArithmeticTarget::B, 4)),
            0x61 => Some(Self::BIT(ArithmeticTarget::C, 4)),
            0x62 => Some(Self::BIT(ArithmeticTarget::D, 4)),
            0x63 => Some(Self::BIT(ArithmeticTarget::E, 4)),
            0x64 => Some(Self::BIT(ArithmeticTarget::H, 4)),
            0x65 => Some(Self::BIT(ArithmeticTarget::L, 4)),
            0x66 => Some(Self::BIT(ArithmeticTarget::HL, 4)),
            0x67 => Some(Self::BIT(ArithmeticTarget::A, 4)),
            // BIT 5
            0x68 => Some(Self::BIT(ArithmeticTarget::B, 5)),
            0x69 => Some(Self::BIT(ArithmeticTarget::C, 5)),
            0x6A => Some(Self::BIT(ArithmeticTarget::D, 5)),
            0x6B => Some(Self::BIT(ArithmeticTarget::E, 5)),
            0x6C => Some(Self::BIT(ArithmeticTarget::H, 5)),
            0x6D => Some(Self::BIT(ArithmeticTarget::L, 5)),
            0x6E => Some(Self::BIT(ArithmeticTarget::HL, 5)),
            0x6F => Some(Self::BIT(ArithmeticTarget::A, 5)),
            // BIT 6
            0x70 => Some(Self::BIT(ArithmeticTarget::B, 6)),
            0x71 => Some(Self::BIT(ArithmeticTarget::C, 6)),
            0x72 => Some(Self::BIT(ArithmeticTarget::D, 6)),
            0x73 => Some(Self::BIT(ArithmeticTarget::E, 6)),
            0x74 => Some(Self::BIT(ArithmeticTarget::H, 6)),
            0x75 => Some(Self::BIT(ArithmeticTarget::L, 6)),
            0x76 => Some(Self::BIT(ArithmeticTarget::HL, 6)),
            0x77 => Some(Self::BIT(ArithmeticTarget::A, 6)),
            // BIT 7
            0x78 => Some(Self::BIT(ArithmeticTarget::B, 7)),
            0x79 => Some(Self::BIT(ArithmeticTarget::C, 7)),
            0x7A => Some(Self::BIT(ArithmeticTarget::D, 7)),
            0x7B => Some(Self::BIT(ArithmeticTarget::E, 7)),
            0x7C => Some(Self::BIT(ArithmeticTarget::H, 7)),
            0x7D => Some(Self::BIT(ArithmeticTarget::L, 7)),
            0x7E => Some(Self::BIT(ArithmeticTarget::HL, 7)),
            0x7F => Some(Self::BIT(ArithmeticTarget::A, 7)),
            // RES 0
            0x80 => Some(Self::RES(ArithmeticTarget::B, 0)),
            0x81 => Some(Self::RES(ArithmeticTarget::C, 0)),
            0x82 => Some(Self::RES(ArithmeticTarget::D, 0)),
            0x83 => Some(Self::RES(ArithmeticTarget::E, 0)),
            0x84 => Some(Self::RES(ArithmeticTarget::H, 0)),
            0x85 => Some(Self::RES(ArithmeticTarget::L, 0)),
            0x86 => Some(Self::RES(ArithmeticTarget::HL, 0)),
            0x87 => Some(Self::RES(ArithmeticTarget::A, 0)),
            // RES 1
            0x88 => Some(Self::RES(ArithmeticTarget::B, 1)),
            0x89 => Some(Self::RES(ArithmeticTarget::C, 1)),
            0x8A => Some(Self::RES(ArithmeticTarget::D, 1)),
            0x8B => Some(Self::RES(ArithmeticTarget::E, 1)),
            0x8C => Some(Self::RES(ArithmeticTarget::H, 1)),
            0x8D => Some(Self::RES(ArithmeticTarget::L, 1)),
            0x8E => Some(Self::RES(ArithmeticTarget::HL, 1)),
            0x8F => Some(Self::RES(ArithmeticTarget::A, 1)),
            // RES 2
            0x90 => Some(Self::RES(ArithmeticTarget::B, 2)),
            0x91 => Some(Self::RES(ArithmeticTarget::C, 2)),
            0x92 => Some(Self::RES(ArithmeticTarget::D, 2)),
            0x93 => Some(Self::RES(ArithmeticTarget::E, 2)),
            0x94 => Some(Self::RES(ArithmeticTarget::H, 2)),
            0x95 => Some(Self::RES(ArithmeticTarget::L, 2)),
            0x96 => Some(Self::RES(ArithmeticTarget::HL, 2)),
            0x97 => Some(Self::RES(ArithmeticTarget::A, 2)),
            // RES 3
            0x98 => Some(Self::RES(ArithmeticTarget::B, 3)),
            0x99 => Some(Self::RES(ArithmeticTarget::C, 3)),
            0x9A => Some(Self::RES(ArithmeticTarget::D, 3)),
            0x9B => Some(Self::RES(ArithmeticTarget::E, 3)),
            0x9C => Some(Self::RES(ArithmeticTarget::H, 3)),
            0x9D => Some(Self::RES(ArithmeticTarget::L, 3)),
            0x9E => Some(Self::RES(ArithmeticTarget::HL, 3)),
            0x9F => Some(Self::RES(ArithmeticTarget::A, 3)),
            // RES 4
            0xA0 => Some(Self::RES(ArithmeticTarget::B, 4)),
            0xA1 => Some(Self::RES(ArithmeticTarget::C, 4)),
            0xA2 => Some(Self::RES(ArithmeticTarget::D, 4)),
            0xA3 => Some(Self::RES(ArithmeticTarget::E, 4)),
            0xA4 => Some(Self::RES(ArithmeticTarget::H, 4)),
            0xA5 => Some(Self::RES(ArithmeticTarget::L, 4)),
            0xA6 => Some(Self::RES(ArithmeticTarget::HL, 4)),
            0xA7 => Some(Self::RES(ArithmeticTarget::A, 4)),
            // RES 5
            0xA8 => Some(Self::RES(ArithmeticTarget::B, 5)),
            0xA9 => Some(Self::RES(ArithmeticTarget::C, 5)),
            0xAA => Some(Self::RES(ArithmeticTarget::D, 5)),
            0xAB => Some(Self::RES(ArithmeticTarget::E, 5)),
            0xAC => Some(Self::RES(ArithmeticTarget::H, 5)),
            0xAD => Some(Self::RES(ArithmeticTarget::L, 5)),
            0xAE => Some(Self::RES(ArithmeticTarget::HL, 5)),
            0xAF => Some(Self::RES(ArithmeticTarget::A, 5)),
            // RES 6
            0xB0 => Some(Self::RES(ArithmeticTarget::B, 6)),
            0xB1 => Some(Self::RES(ArithmeticTarget::C, 6)),
            0xB2 => Some(Self::RES(ArithmeticTarget::D, 6)),
            0xB3 => Some(Self::RES(ArithmeticTarget::E, 6)),
            0xB4 => Some(Self::RES(ArithmeticTarget::H, 6)),
            0xB5 => Some(Self::RES(ArithmeticTarget::L, 6)),
            0xB6 => Some(Self::RES(ArithmeticTarget::HL, 6)),
            0xB7 => Some(Self::RES(ArithmeticTarget::A, 6)),
            // RES 7
            0xB8 => Some(Self::RES(ArithmeticTarget::B, 7)),
            0xB9 => Some(Self::RES(ArithmeticTarget::C, 7)),
            0xBA => Some(Self::RES(ArithmeticTarget::D, 7)),
            0xBB => Some(Self::RES(ArithmeticTarget::E, 7)),
            0xBC => Some(Self::RES(ArithmeticTarget::H, 7)),
            0xBD => Some(Self::RES(ArithmeticTarget::L, 7)),
            0xBE => Some(Self::RES(ArithmeticTarget::HL, 7)),
            0xBF => Some(Self::RES(ArithmeticTarget::A, 7)),
            // SET 0
            0xC0 => Some(Self::SET(ArithmeticTarget::B, 0)),
            0xC1 => Some(Self::SET(ArithmeticTarget::C, 0)),
            0xC2 => Some(Self::SET(ArithmeticTarget::D, 0)),
            0xC3 => Some(Self::SET(ArithmeticTarget::E, 0)),
            0xC4 => Some(Self::SET(ArithmeticTarget::H, 0)),
            0xC5 => Some(Self::SET(ArithmeticTarget::L, 0)),
            0xC6 => Some(Self::SET(ArithmeticTarget::HL, 0)),
            0xC7 => Some(Self::SET(ArithmeticTarget::A, 0)),
            // SET 1
            0xC8 => Some(Self::SET(ArithmeticTarget::B, 1)),
            0xC9 => Some(Self::SET(ArithmeticTarget::C, 1)),
            0xCA => Some(Self::SET(ArithmeticTarget::D, 1)),
            0xCB => Some(Self::SET(ArithmeticTarget::E, 1)),
            0xCC => Some(Self::SET(ArithmeticTarget::H, 1)),
            0xCD => Some(Self::SET(ArithmeticTarget::L, 1)),
            0xCE => Some(Self::SET(ArithmeticTarget::HL, 1)),
            0xCF => Some(Self::SET(ArithmeticTarget::A, 1)),
            // SET 2
            0xD0 => Some(Self::SET(ArithmeticTarget::B, 2)),
            0xD1 => Some(Self::SET(ArithmeticTarget::C, 2)),
            0xD2 => Some(Self::SET(ArithmeticTarget::D, 2)),
            0xD3 => Some(Self::SET(ArithmeticTarget::E, 2)),
            0xD4 => Some(Self::SET(ArithmeticTarget::H, 2)),
            0xD5 => Some(Self::SET(ArithmeticTarget::L, 2)),
            0xD6 => Some(Self::SET(ArithmeticTarget::HL, 2)),
            0xD7 => Some(Self::SET(ArithmeticTarget::A, 2)),
            // SET 3
            0xD8 => Some(Self::SET(ArithmeticTarget::B, 3)),
            0xD9 => Some(Self::SET(ArithmeticTarget::C, 3)),
            0xDA => Some(Self::SET(ArithmeticTarget::D, 3)),
            0xDB => Some(Self::SET(ArithmeticTarget::E, 3)),
            0xDC => Some(Self::SET(ArithmeticTarget::H, 3)),
            0xDD => Some(Self::SET(ArithmeticTarget::L, 3)),
            0xDE => Some(Self::SET(ArithmeticTarget::HL, 3)),
            0xDF => Some(Self::SET(ArithmeticTarget::A, 3)),
            // SET 4
            0xE0 => Some(Self::SET(ArithmeticTarget::B, 4)),
            0xE1 => Some(Self::SET(ArithmeticTarget::C, 4)),
            0xE2 => Some(Self::SET(ArithmeticTarget::D, 4)),
            0xE3 => Some(Self::SET(ArithmeticTarget::E, 4)),
            0xE4 => Some(Self::SET(ArithmeticTarget::H, 4)),
            0xE5 => Some(Self::SET(ArithmeticTarget::L, 4)),
            0xE6 => Some(Self::SET(ArithmeticTarget::HL, 4)),
            0xE7 => Some(Self::SET(ArithmeticTarget::A, 4)),
            // SET 5
            0xE8 => Some(Self::SET(ArithmeticTarget::B, 5)),
            0xE9 => Some(Self::SET(ArithmeticTarget::C, 5)),
            0xEA => Some(Self::SET(ArithmeticTarget::D, 5)),
            0xEB => Some(Self::SET(ArithmeticTarget::E, 5)),
            0xEC => Some(Self::SET(ArithmeticTarget::H, 5)),
            0xED => Some(Self::SET(ArithmeticTarget::L, 5)),
            0xEE => Some(Self::SET(ArithmeticTarget::HL, 5)),
            0xEF => Some(Self::SET(ArithmeticTarget::A, 5)),
            // SET 6
            0xF0 => Some(Self::SET(ArithmeticTarget::B, 6)),
            0xF1 => Some(Self::SET(ArithmeticTarget::C, 6)),
            0xF2 => Some(Self::SET(ArithmeticTarget::D, 6)),
            0xF3 => Some(Self::SET(ArithmeticTarget::E, 6)),
            0xF4 => Some(Self::SET(ArithmeticTarget::H, 6)),
            0xF5 => Some(Self::SET(ArithmeticTarget::L, 6)),
            0xF6 => Some(Self::SET(ArithmeticTarget::HL, 6)),
            0xF7 => Some(Self::SET(ArithmeticTarget::A, 6)),
            // SET 7
            0xF8 => Some(Self::SET(ArithmeticTarget::B, 7)),
            0xF9 => Some(Self::SET(ArithmeticTarget::C, 7)),
            0xFA => Some(Self::SET(ArithmeticTarget::D, 7)),
            0xFB => Some(Self::SET(ArithmeticTarget::E, 7)),
            0xFC => Some(Self::SET(ArithmeticTarget::H, 7)),
            0xFD => Some(Self::SET(ArithmeticTarget::L, 7)),
            0xFE => Some(Self::SET(ArithmeticTarget::HL, 7)),
            0xFF => Some(Self::SET(ArithmeticTarget::A, 7)),
        }
    }
}
